# Generated by Django 4.0.1 on 2022-02-07 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='transmition',
            new_name='transmission',
        ),
    ]
